// auth action types
export const PROCESSING_AUTH = 'PROCESSING_AUTH';
export const PROCESSING_AUTH_DONE = 'PROCESSING_AUTH_DONE';
// export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const IS_SIGNING_UP = 'IS_SIGNING_UP';
export const SIGN_UP_MEMBER_SUCCESS = 'SIGN_UP_MEMBER_SUCCESS';
export const SIGN_UP_MEMBER_FAILED = 'SIGN_UP_MEMBER_FAILED';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAILED';

export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_FAIL = 'UPLOAD_AVATAR_FAILED';

export const MODE_EDIT_PROFILE_ON = 'MODE_EDIT_PROFILE_ON';
export const MODE_EDIT_PROFILE_DONE = 'MODE_EDIT_PROFILE_DONE';

// main reducer types
export const UPDATE_SEARCH_OPTIONS = 'UPDATE_SEARCH_OPTIONS';

export const FETCH_LABS = 'FETCH_LABS_BY';
export const FETCH_LABS_SUCCESS = 'FETCH_LABS_SUCCESS';
export const FETCH_LABS_FAILED = 'FETCH_LABS_FAILED';
export const FETCHING_LABS = 'FETCHING_LABS';
export const FETCHING_LABS_DONE = 'FETCHING_LABS_DONE';

export const FETCH_PROJECT_RECRUITMENTS = 'FETCH_PROJECT_RECRUITMENTS';
export const FETCH_PROJECT_RECRUITMENTS_SUCCESS =
  'FETCH_RECRUITMENT_PROJECTS_SUCCESS';
export const FETCH_PROJECT_RECRUITMENTS_FAILED =
  'FETCH_RECRUITMENT_PROJECTS_FAILED';
export const FETCHING_PROJECT_RECRUITMENTS = 'FETCHING_PROJECT_RECRUITMENTS';
export const FETCHING_PROJECT_RECRUITMENTS_DONE =
  'FETCHING_PROJECT_RECRUITMENTS_DONE';

export const FETCH_ACTIVE_ACTIVITIES = 'FETCH_ACTIVE_ACTIVITIES';
export const FETCH_ACTIVE_ACTIVITIES_SUCCESS =
  'FETCH_ACTIVE_ACTIVITIES_SUCCESS';
export const FETCH_ACTIVE_ACTIVITIES_FAILED = 'FETCH_ACTIVE_ACTIVITIES_FAILED';
export const FETCHING_ACTIVE_ACTIVITIES = 'FETCHING_ACTIVE_ACTIVITIES';
export const FETCHING_ACTIVE_ACTIVITIES_DONE =
  'FETCHING_ACTIVE_ACTIVITIES_DONE';

export const FETCH_LAB_RECRUITMENTS = 'FETCH_LAB_RECRUITMENTS';
export const FETCH_LAB_RECRUITMENTS_SUCCESS = 'FETCH_LAB_RECRUITMENTS_SUCCESS';
export const FETCH_LAB_RECRUITMENTS_FAILED = 'FETCH_LAB_RECRUITMENTS_FAILED';
export const FETCHING_LAB_RECRUITMENTS = 'FETCHING_LAB_RECRUITMENTS';
export const FETCHING_LAB_RECRUITMENTS_DONE = 'FETCHING_LAB_RECRUITMENTS_DONE';

export const FETCH_HIGHLIGHT_LABS = 'FETCH_HIGHLIGHT_LABS';
export const UPDATE_FETCH_HIGHLIGHT_LABS_STATUS =
  'UPDATE_FETCH_HIGHLIGHT_LABS_STATUS';
export const FETCHING_HIGHLIGHT_LABS_DONE = 'FETCHING_HIGHLIGHT_LABS_DONE';
export const FETCH_HIGHLIGHT_LABS_SUCCESS = 'FETCH_HIGHLIGHT_LABS_SUCCESS';
export const FETCH_HIGHLIGHT_LABS_FAILED = 'FETCH_HIGHLIGHT_LABS_FAILED';
